###cobalah
POST http://localhost:8081/greet
content-type: application/json

{
    "name": "prabowo"
}

###
GET http://localhost:8081/hello

###
GET http://localhost:8081/user/10

###
GET http://localhost:8081/welcome
###
POST http://localhost:8081/register
content-type: application/json

{
    "username": "jokowi"
}

###
GET http://localhost:8081/welcome

###
GET http://localhost:8081/version

###
POST http://localhost:8081/users/register
Content-Type: application/json

{
    "username": "budi",
    "email": "budi@gmail.com"
}

###
GET http://localhost:8081/users/1

###
POST http://localhost:8081/users/register2
Content-Type: application/json

{
    "username": "budi",
    "email": "budi@gmail.com"
}