###cobalah
POST http://localhost:8081/greet
content-type: application/json

{
    "name": "prabowo"
}

###
GET http://localhost:8081/hello

###
GET http://localhost:8081/user/10

###
GET http://localhost:8081/welcome
###
POST http://localhost:8081/register
content-type: application/json

{
    "username": "jokowi"
}

###
GET http://localhost:8081/welcome

###
GET http://localhost:8081/version